services:
  web:
    image: ghcr.io/nrf24l01/silaeder-conf/nginx:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${NGINX_BIND_IP}:6001:80"